//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssesmentWeb.HOME.DATABASE_UPDATE {
    
    
    public partial class dbUpdate {
        
        /// <summary>
        /// RTOnav control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AssesmentWeb.HOME.DATABASE_UPDATE.RTOnav RTOnav;
        
        /// <summary>
        /// RTOSideNavbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AssesmentWeb.HOME.DATABASE_UPDATE.RTOSideNavbar RTOSideNavbar;
    }
}
